log:
  level: info
  file: /tmp/mosdns.log

plugins:
  - tag: local
    type: sequence
    args:
      - matches: qtype 65
        exec: reject 0
      - exec: forward https://223.5.5.5/dns-query

  - tag: remote
    type: sequence
    args:
      - matches: qtype 28 65
        exec: reject 0
      - exec: forward https://208.67.222.222/dns-query

  - tag: local_udp
    type: udp_server
    args:
      entry: local
      listen: 127.0.0.1:5522

  - tag: remote_udp
    type: udp_server
    args:
      entry: remote
      listen: 127.0.0.1:5533
