
name: Zero Runs

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Cleanup Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 0
        
      - name: Cleanup Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
